import type { ThemePreset } from '../types';

export const businessPresets: ThemePreset[] = [
  {
    id: 'finance-blue',
    name: 'أزرق مالي',
    description: 'الأزرق المصرفي الرسمي. احترافي وموثوق للأنظمة المالية.',
    colors: ['#1d4ed8', '#3b82f6', '#eff6ff'],
    previewColor: '#f0f6ff',
    accent: '#1d4ed8',
    isDark: false,
    category: 'accounting',
    emoji: '🏦',
    cssVars: {
      '--app-bg': '#edf2fd',
      '--app-surface': '#f5f8ff',
      '--app-surface-hover': '#dce6f8',
      '--app-border': '#bccee8',
      '--app-text': '#0f1d3a',
      '--app-text-secondary': '#405880',
      '--accent': '#1d4ed8',
    }
  },
  {
    id: 'finance-green',
    name: 'أخضر مالي',
    description: 'أخضر الأرباح والنمو. يوحي بالاستقرار المالي والنجاح.',
    colors: ['#16a34a', '#22c55e', '#f0fdf4'],
    previewColor: '#f0fdf4',
    accent: '#16a34a',
    isDark: false,
    category: 'accounting',
    emoji: '💰',
    cssVars: {
      '--app-bg': '#edf8f0',
      '--app-surface': '#f5fdf7',
      '--app-surface-hover': '#dcf2e2',
      '--app-border': '#b8dec5',
      '--app-text': '#0c2a15',
      '--app-text-secondary': '#326845',
      '--accent': '#16a34a',
    }
  },
  {
    id: 'finance-dark',
    name: 'ليل مالي',
    description: 'وضع مظلم احترافي للمحاسبين. أرقام واضحة وتباين ممتاز.',
    colors: ['#4ade80', '#22c55e', '#0a1a10'],
    previewColor: '#0a1a10',
    accent: '#4ade80',
    isDark: true,
    category: 'accounting',
    emoji: '📈',
    cssVars: {
      '--app-bg': '#080f0c',
      '--app-surface': '#101c15',
      '--app-surface-hover': '#1a2e22',
      '--app-border': '#243d2e',
      '--app-text': '#d8f5e2',
      '--app-text-secondary': '#70c090',
      '--accent': '#4ade80',
    }
  },
  {
    id: 'finance-slate',
    name: 'رمادي رسمي',
    description: 'رمادي محايد احترافي. مثالي للتدقيق والتقارير المالية.',
    colors: ['#475569', '#64748b', '#f1f5f9'],
    previewColor: '#f8fafc',
    accent: '#475569',
    isDark: false,
    category: 'accounting',
    emoji: '📋',
    cssVars: {
      '--app-bg': '#eef1f5',
      '--app-surface': '#f8fafc',
      '--app-surface-hover': '#e2e8f0',
      '--app-border': '#c8d0dc',
      '--app-text': '#141c28',
      '--app-text-secondary': '#4a5568',
      '--accent': '#475569',
    }
  },
  {
    id: 'finance-teal',
    name: 'تركوازي مالي',
    description: 'تركوازي عصري للأنظمة المالية الحديثة. حيوية واحترافية.',
    colors: ['#0d9488', '#14b8a6', '#f0fdfa'],
    previewColor: '#f0fdfa',
    accent: '#0d9488',
    isDark: false,
    category: 'accounting',
    emoji: '💹',
    cssVars: {
      '--app-bg': '#e8f8f5',
      '--app-surface': '#f0fdfa',
      '--app-surface-hover': '#d8f0ec',
      '--app-border': '#b0dcd5',
      '--app-text': '#0a2824',
      '--app-text-secondary': '#2d706a',
      '--accent': '#0d9488',
    }
  },
  {
    id: 'corporate-slate',
    name: 'شركة رمادية',
    description: 'رمادي حديث أنيق للشركات الناشئة والتقنية.',
    colors: ['#6366f1', '#818cf8', '#eef2ff'],
    previewColor: '#eef2ff',
    accent: '#6366f1',
    isDark: false,
    category: 'corporate',
    emoji: '🏢',
    cssVars: {
      '--app-bg': '#eef2ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#e0e7ff',
      '--app-border': '#c7d2fe',
      '--app-text': '#1e1b4b',
      '--app-text-secondary': '#4338ca',
      '--accent': '#6366f1',
    }
  },
  {
    id: 'corporate-slate-dark',
    name: 'ليل الشركة',
    description: 'وضع مظلم أنيق للشركات التقنية الحديثة.',
    colors: ['#818cf8', '#6366f1', '#1e1b4b'],
    previewColor: '#1e1b4b',
    accent: '#818cf8',
    isDark: true,
    category: 'corporate',
    emoji: '💻',
    cssVars: {
      '--app-bg': '#0f0f1a',
      '--app-surface': '#1a1a2e',
      '--app-surface-hover': '#252542',
      '--app-border': '#363654',
      '--app-text': '#e0e7ff',
      '--app-text-secondary': '#818cf8',
      '--accent': '#818cf8',
    }
  },
  {
    id: 'modern-teal',
    name: 'تركواز عصري',
    description: 'تركواز حداثي نظيف للتطبيقات المالية.',
    colors: ['#14b8a6', '#2dd4bf', '#f0fdfa'],
    previewColor: '#f0fdfa',
    accent: '#0d9488',
    isDark: false,
    category: 'corporate',
    emoji: '🎯',
    cssVars: {
      '--app-bg': '#f0fdfa',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#ccfbf1',
      '--app-border': '#99f6e4',
      '--app-text': '#042f2e',
      '--app-text-secondary': '#115e59',
      '--accent': '#0d9488',
    }
  },
  {
    id: 'modern-cyan',
    name: 'سيان حديث',
    description: 'أزرق سيان نابض بالحياة للتطبيقات الحيوية.',
    colors: ['#06b6d4', '#22d3ee', '#ecfeff'],
    previewColor: '#ecfeff',
    accent: '#0891b2',
    isDark: false,
    category: 'corporate',
    emoji: '💠',
    cssVars: {
      '--app-bg': '#ecfeff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#cffafe',
      '--app-border': '#a5f3fc',
      '--app-text': '#083344',
      '--app-text-secondary': '#155e75',
      '--accent': '#0891b2',
    }
  },
  {
    id: 'bento-pro',
    name: 'بينتو احترافي',
    description: 'تقسيمات هندسية دقيقة مع تباين عالي. مثالي للوحات البيانات المعقدة.',
    colors: ['#0f172a', '#f1f5f9', '#3b82f6'],
    previewColor: '#f1f5f9',
    accent: '#2563eb',
    isDark: false,
    category: 'bento',
    emoji: '📊',
    cssVars: {
      '--app-bg': '#f1f5f9',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f8fafc',
      '--app-border': '#e2e8f0',
      '--app-text': '#0f172a',
      '--app-text-secondary': '#64748b',
      '--accent': '#2563eb',
    }
  }
];
