import type { ThemePreset } from '../types';

export const creativePresets: ThemePreset[] = [
  {
    id: 'emerald-forest',
    name: 'غابة زمردية',
    description: 'أخضر زمردي غني. إحساس بالطبيعة والانتعاش.',
    colors: ['#059669', '#10b981', '#ecfdf5'],
    previewColor: '#f0fdf4',
    accent: '#059669',
    isDark: false,
    category: 'nature',
    emoji: '🌿',
    cssVars: {
      '--app-bg': '#ebf7f0',
      '--app-surface': '#f5fdf8',
      '--app-surface-hover': '#daf0e4',
      '--app-border': '#b8dcc8',
      '--app-text': '#0e2a1c',
      '--app-text-secondary': '#367a55',
      '--accent': '#059669',
    }
  },
  {
    id: 'deep-forest',
    name: 'ليل الغابة',
    description: 'أخضر غامق غني مع ظلال الليل. هدوء واحترافية.',
    colors: ['#34d399', '#10b981', '#0f2922'],
    previewColor: '#0a1f17',
    accent: '#34d399',
    isDark: true,
    category: 'nature',
    emoji: '🌲',
    cssVars: {
      '--app-bg': '#080f0c',
      '--app-surface': '#10201a',
      '--app-surface-hover': '#183028',
      '--app-border': '#204038',
      '--app-text': '#d0f0e0',
      '--app-text-secondary': '#60b88a',
      '--accent': '#34d399',
    }
  },
  {
    id: 'crimson-dark',
    name: 'قرمزي مظلم',
    description: 'أحمر قرمزي عميق في وضع مظلم. قوة وتميّز.',
    colors: ['#f87171', '#ef4444', '#1c0a0a'],
    previewColor: '#170808',
    accent: '#f87171',
    isDark: true,
    category: 'bold',
    emoji: '🔥',
    cssVars: {
      '--app-bg': '#100606',
      '--app-surface': '#1c0c0c',
      '--app-surface-hover': '#2c1414',
      '--app-border': '#401818',
      '--app-text': '#f5d8d8',
      '--app-text-secondary': '#d07070',
      '--accent': '#f87171',
    }
  },
  {
    id: 'sunset-orange',
    name: 'غروب برتقالي',
    description: 'ألوان الغروب الدافئة. طاقة إيجابية وحيوية.',
    colors: ['#f97316', '#fb923c', '#fff7ed'],
    previewColor: '#fff7ed',
    accent: '#ea6c0c',
    isDark: false,
    category: 'bold',
    emoji: '🌅',
    cssVars: {
      '--app-bg': '#fef0e0',
      '--app-surface': '#fff8ef',
      '--app-surface-hover': '#fde8d0',
      '--app-border': '#f0d0a8',
      '--app-text': '#3a1e08',
      '--app-text-secondary': '#8a5a28',
      '--accent': '#ea6c0c',
    }
  },
  {
    id: 'night-amethyst',
    name: 'ليلي ياقوتي',
    description: 'ياقوت أرجواني داكن مع بريق星光.',
    colors: ['#a855f7', '#c084fc', '#2e1065'],
    previewColor: '#2e1065',
    accent: '#a855f7',
    isDark: true,
    category: 'night',
    emoji: '✨',
    cssVars: {
      '--app-bg': '#0f0a1f',
      '--app-surface': '#1a1229',
      '--app-surface-hover': '#251a38',
      '--app-border': '#3d2a52',
      '--app-text': '#f3e8ff',
      '--app-text-secondary': '#c084fc',
      '--accent': '#a855f7',
    }
  },
  {
    id: 'night-sapphire',
    name: 'ليلي ياقوت أزرق',
    description: 'ياقوت أزرق داكن مع لمسات فيروزية.',
    colors: ['#38bdf8', '#7dd3fc', '#0c4a6e'],
    previewColor: '#0c4a6e',
    accent: '#38bdf8',
    isDark: true,
    category: 'night',
    emoji: '💎',
    cssVars: {
      '--app-bg': '#071a2e',
      '--app-surface': '#0f2847',
      '--app-surface-hover': '#163660',
      '--app-border': '#1e4976',
      '--app-text': '#e0f2fe',
      '--app-text-secondary': '#7dd3fc',
      '--accent': '#38bdf8',
    }
  },
  {
    id: 'night-gold',
    name: 'ليل ذهبي',
    description: 'ذهب داكن مع لمسات برتقالية ليلية.',
    colors: ['#fbbf24', '#fcd34d', '#451a03'],
    previewColor: '#451a03',
    accent: '#fbbf24',
    isDark: true,
    category: 'night',
    emoji: '🌟',
    cssVars: {
      '--app-bg': '#1a1205',
      '--app-surface': '#2a1c08',
      '--app-surface-hover': '#3d2810',
      '--app-border': '#5c3d18',
      '--app-text': '#fef3c7',
      '--app-text-secondary': '#fbbf24',
      '--accent': '#fbbf24',
    }
  },
  {
    id: 'night-rose',
    name: 'ليلي وردي',
    description: 'وردي داكن أنيق مع تدرجات أرجوانية.',
    colors: ['#fb7185', '#fb923c', '#881337'],
    previewColor: '#881337',
    accent: '#fb7185',
    isDark: true,
    category: 'night',
    emoji: '🌹',
    cssVars: {
      '--app-bg': '#1a0812',
      '--app-surface': '#2d101c',
      '--app-surface-hover': '#401828',
      '--app-border': '#5c2036',
      '--app-text': '#ffe4e6',
      '--app-text-secondary': '#fb7185',
      '--accent': '#fb7185',
    }
  },
  {
    id: 'crystal-glass',
    name: 'كريستال زجاجي',
    description: 'شفافية ناصعة مع بلور ناعم. مظهر عصري وخفيف جداً.',
    colors: ['#ffffff', '#f0f9ff', '#e0f2fe'],
    previewColor: '#ffffff',
    accent: '#3b82f6',
    isDark: false,
    category: 'glass',
    emoji: '💎',
    cssVars: {
      '--app-bg': '#f8fafc',
      '--app-surface': 'rgba(255, 255, 255, 0.7)',
      '--app-surface-hover': 'rgba(255, 255, 255, 0.9)',
      '--app-border': 'rgba(255, 255, 255, 0.5)',
      '--app-text': '#0f172a',
      '--app-text-secondary': '#475569',
      '--accent': '#3b82f6',
    }
  },
  {
    id: 'frosted-obsidian',
    name: 'أوبسيديان مثلج',
    description: 'زجاج داكن مع تأثير الثلج. فخامة وهدوء في الوضع الليلي.',
    colors: ['#0f172a', '#1e293b', '#334155'],
    previewColor: '#0f172a',
    accent: '#818cf8',
    isDark: true,
    category: 'glass',
    emoji: '🌌',
    cssVars: {
      '--app-bg': '#020617',
      '--app-surface': 'rgba(15, 23, 42, 0.7)',
      '--app-surface-hover': 'rgba(30, 41, 59, 0.8)',
      '--app-border': 'rgba(255, 255, 255, 0.1)',
      '--app-text': '#f1f5f9',
      '--app-text-secondary': '#94a3b8',
      '--accent': '#818cf8',
    }
  },
  {
    id: 'aurora-glass',
    name: 'أورورا زجاجي',
    description: 'تدرجات ألوان الشفق القطبي خلف زجاج شفاف. إبداع وحيوية.',
    colors: ['#4f46e5', '#ec4899', '#06b6d4'],
    previewColor: '#4f46e5',
    accent: '#6366f1',
    isDark: false,
    category: 'glass',
    emoji: '🌈',
    cssVars: {
      '--app-bg': 'linear-gradient(135deg, #f5f3ff 0%, #fdf2f8 50%, #ecfeff 100%)',
      '--app-surface': 'rgba(255, 255, 255, 0.6)',
      '--app-surface-hover': 'rgba(255, 255, 255, 0.8)',
      '--app-border': 'rgba(255, 255, 255, 0.4)',
      '--app-text': '#1e1b4b',
      '--app-text-secondary': '#4338ca',
      '--accent': '#6366f1',
    }
  }
];
