import { ThemePreset } from '../types';

export const premiumPresets: ThemePreset[] = [
  {
    id: 'emerald-pro',
    name: 'زمردي احترافي',
    description: 'مزيج من ألوان الغابات الزمردية العميقة. هدوء وفخامة في كل وضع.',
    colors: ['#059669', '#10b981', '#ecfdf5'],
    previewColor: '#059669',
    accent: '#059669',
    isDark: false,
    category: 'premium',
    emoji: '🌿',
    cssVars: {
      '--app-bg': '#f0fdf4',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#dcfce7',
      '--app-border': '#bbf7d0',
      '--app-text': '#064e3b',
      '--app-text-secondary': '#047857',
      '--accent': '#059669',
    },
    light: {
      '--app-bg': '#f0fdf4',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#dcfce7',
      '--app-border': '#bbf7d0',
      '--app-text': '#064e3b',
      '--app-text-secondary': '#047857',
      '--accent': '#059669',
    },
    dark: {
      '--app-bg': '#020617',
      '--app-surface': '#0f172a',
      '--app-surface-hover': '#1e293b',
      '--app-border': '#1e293b',
      '--app-text': '#f1f5f9',
      '--app-text-secondary': '#94a3b8',
      '--accent': '#10b981',
    }
  },
  {
    id: 'sapphire-pro',
    name: 'ياقوت أزرق احترافي',
    description: 'أزرق كحلي عميق مع لمسات فضية باردة. للمكاتب الرسمية والمؤسسات.',
    colors: ['#1e40af', '#3b82f6', '#eff6ff'],
    previewColor: '#1e40af',
    accent: '#1e40af',
    isDark: false,
    category: 'premium',
    emoji: '💎',
    cssVars: {
      '--app-bg': '#f8fafc',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f1f5f9',
      '--app-border': '#e2e8f0',
      '--app-text': '#0f172a',
      '--app-text-secondary': '#475569',
      '--accent': '#1e40af',
    },
    light: {
      '--app-bg': '#f8fafc',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f1f5f9',
      '--app-border': '#e2e8f0',
      '--app-text': '#0f172a',
      '--app-text-secondary': '#475569',
      '--accent': '#1e40af',
    },
    dark: {
      '--app-bg': '#0a0f1e',
      '--app-surface': '#141b2d',
      '--app-surface-hover': '#1e293b',
      '--app-border': '#1e293b',
      '--app-text': '#e2e8f0',
      '--app-text-secondary': '#94a3b8',
      '--accent': '#3b82f6',
    }
  },
  {
    id: 'amethyst-pro',
    name: 'أرجواني ملكي احترافي',
    description: 'أناقة اللافندر الفاخر مع تدرجات رويال. لمسة إبداعية متميزة.',
    colors: ['#6d28d9', '#8b5cf6', '#f5f3ff'],
    previewColor: '#6d28d9',
    accent: '#6d28d9',
    isDark: false,
    category: 'premium',
    emoji: '🔮',
    cssVars: {
      '--app-bg': '#f5f3ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#ede9fe',
      '--app-border': '#ddd6fe',
      '--app-text': '#2e1065',
      '--app-text-secondary': '#6d28d9',
      '--accent': '#6d28d9',
    },
    light: {
      '--app-bg': '#f5f3ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#ede9fe',
      '--app-border': '#ddd6fe',
      '--app-text': '#2e1065',
      '--app-text-secondary': '#6d28d9',
      '--accent': '#6d28d9',
    },
    dark: {
      '--app-bg': '#0f0a1f',
      '--app-surface': '#1a1229',
      '--app-surface-hover': '#251a38',
      '--app-border': '#3d2a52',
      '--app-text': '#f3e8ff',
      '--app-text-secondary': '#c084fc',
      '--accent': '#a855f7',
    }
  },
  {
    id: 'obsidian-pro',
    name: 'أوبسيديان فاخر',
    description: 'تباين عالٍ يجمع بين الفولاذ المصقول والأسود الفاخر. لمحبي الحداثة.',
    colors: ['#0f172a', '#334155', '#f8fafc'],
    previewColor: '#0f172a',
    accent: '#0f172a',
    isDark: false,
    category: 'premium',
    emoji: '🖤',
    cssVars: {
      '--app-bg': '#f1f5f9',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f8fafc',
      '--app-border': '#cbd5e1',
      '--app-text': '#020617',
      '--app-text-secondary': '#475569',
      '--accent': '#0f172a',
    },
    light: {
      '--app-bg': '#f1f5f9',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f8fafc',
      '--app-border': '#cbd5e1',
      '--app-text': '#020617',
      '--app-text-secondary': '#475569',
      '--accent': '#0f172a',
    },
    dark: {
      '--app-bg': '#020617',
      '--app-surface': '#0a0a0a',
      '--app-surface-hover': '#171717',
      '--app-border': '#262626',
      '--app-text': '#fafafa',
      '--app-text-secondary': '#a3a3a3',
      '--accent': '#ffffff',
    }
  },
  {
    id: 'clean-white',
    name: 'النظام الناصع',
    description: 'تصميم رسمي نظيف يركز على سهولة القراءة والوضوح التام.',
    colors: ['#3b82f6', '#60a5fa', '#f8fafc'],
    previewColor: '#ffffff',
    accent: '#3b82f6',
    isDark: false,
    category: 'classic',
    emoji: '⚪',
    cssVars: {
      '--app-bg': '#f4f6f9',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#eef1f6',
      '--app-border': '#d5dbe5',
      '--app-text': '#1a2332',
      '--app-text-secondary': '#5a6a7e',
      '--accent': '#3b82f6',
    }
  },
  {
    id: 'midnight-ocean',
    name: 'عمق المحيط',
    description: 'تباين مريح للعين في الإضاءة المنخفضة مع لمسات زرقاء.',
    colors: ['#38bdf8', '#3b82f6', '#1e293b'],
    previewColor: '#0f172a',
    accent: '#38bdf8',
    isDark: true,
    category: 'classic',
    emoji: '🌊',
    cssVars: {
      '--app-bg': '#0c1524',
      '--app-surface': '#141f33',
      '--app-surface-hover': '#1c2d48',
      '--app-border': '#253854',
      '--app-text': '#e8edf5',
      '--app-text-secondary': '#8da0be',
      '--accent': '#38bdf8',
    }
  }
];
