import { ThemePreset } from '../types';

export const seasonalAndArtisticPresets: ThemePreset[] = [
  {
    id: 'spring-pink',
    name: 'وردي ربيعي',
    description: 'وردي ربيعي نابض بالحياة والأمل.',
    colors: ['#ec4899', '#f472b6', '#fdf2f8'],
    previewColor: '#fdf2f8',
    accent: '#db2777',
    isDark: false,
    category: 'seasonal',
    emoji: '🌸',
    cssVars: {
      '--app-bg': '#fdf2f8',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#fce7f3',
      '--app-border': '#fbcfe8',
      '--app-text': '#831843',
      '--app-text-secondary': '#be185d',
      '--accent': '#db2777',
    }
  },
  {
    id: 'summer-cyan',
    name: 'سيان صيفي',
    description: 'أزرق صيفي منعش مع لمسات فيروزية.',
    colors: ['#06b6d4', '#22d3ee', '#ecfeff'],
    previewColor: '#ecfeff',
    accent: '#0891b2',
    isDark: false,
    category: 'seasonal',
    emoji: '☀️',
    cssVars: {
      '--app-bg': '#ecfeff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#cffafe',
      '--app-border': '#a5f3fc',
      '--app-text': '#083344',
      '--app-text-secondary': '#155e75',
      '--accent': '#0891b2',
    }
  },
  {
    id: 'autumn-orange',
    name: 'برتقالي خريفي',
    description: 'برتقالي دافئ بألوان أوراق الخريف.',
    colors: ['#ea580c', '#f97316', '#fff7ed'],
    previewColor: '#fff7ed',
    accent: '#c2410c',
    isDark: false,
    category: 'seasonal',
    emoji: '🍂',
    cssVars: {
      '--app-bg': '#fff7ed',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#ffedd5',
      '--app-border': '#fed7aa',
      '--app-text': '#7c2d12',
      '--app-text-secondary': '#c2410c',
      '--accent': '#c2410c',
    }
  },
  {
    id: 'winter-blue',
    name: 'أزرق شتوي',
    description: 'أزرق بارد مع لمسات ثلجية.',
    colors: ['#3b82f6', '#60a5fa', '#eff6ff'],
    previewColor: '#eff6ff',
    accent: '#2563eb',
    isDark: false,
    category: 'seasonal',
    emoji: '❄️',
    cssVars: {
      '--app-bg': '#eff6ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#dbeafe',
      '--app-border': '#bfdbfe',
      '--app-text': '#1e3a8a',
      '--app-text-secondary': '#1d4ed8',
      '--accent': '#2563eb',
    }
  },
  {
    id: 'artist-indigo',
    name: 'أنديغو فني',
    description: 'أنديغو عميق مع لمسات بنفسجية.',
    colors: ['#6366f1', '#818cf8', '#e0e7ff'],
    previewColor: '#e0e7ff',
    accent: '#4f46e5',
    isDark: false,
    category: 'artistic',
    emoji: '🎨',
    cssVars: {
      '--app-bg': '#e0e7ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#c7d2fe',
      '--app-border': '#a5b4fc',
      '--app-text': '#312e81',
      '--app-text-secondary': '#4f46e5',
      '--accent': '#4f46e5',
    }
  },
  {
    id: 'artist-lavender',
    name: 'لافندر فني',
    description: 'خزامي ناعم مع لمسات فيروزية.',
    colors: ['#a78bfa', '#c4b5fd', '#f5f3ff'],
    previewColor: '#f5f3ff',
    accent: '#8b5cf6',
    isDark: false,
    category: 'artistic',
    emoji: '🖌️',
    cssVars: {
      '--app-bg': '#f5f3ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#ede9fe',
      '--app-border': '#ddd6fe',
      '--app-text': '#4c1d95',
      '--app-text-secondary': '#7c3aed',
      '--accent': '#8b5cf6',
    }
  },
  {
    id: 'minimal-gray',
    name: 'رمادي بسيط',
    description: 'بسيط ونظيف مع لمسات أرجوانية خفيفة.',
    colors: ['#a1a1aa', '#71717a', '#fafafa'],
    previewColor: '#fafafa',
    accent: '#71717a',
    isDark: false,
    category: 'artistic',
    emoji: '⬜',
    cssVars: {
      '--app-bg': '#fafafa',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f4f4f5',
      '--app-border': '#e4e4e7',
      '--app-text': '#27272a',
      '--app-text-secondary': '#52525b',
      '--accent': '#71717a',
    }
  },
  {
    id: 'health-medical',
    name: 'طبي صحي',
    description: 'أخضر طبي هادئ للمنشآت الصحية.',
    colors: ['#10b981', '#34d399', '#ecfdf5'],
    previewColor: '#ecfdf5',
    accent: '#059669',
    isDark: false,
    category: 'industry',
    emoji: '🏥',
    cssVars: {
      '--app-bg': '#ecfdf5',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#d1fae5',
      '--app-border': '#a7f3d0',
      '--app-text': '#064e3b',
      '--app-text-secondary': '#047857',
      '--accent': '#059669',
    }
  },
  {
    id: 'food-restaurant',
    name: 'مطاعم وطعام',
    description: 'برتقالي دافئ للمطاعم والوجبات.',
    colors: ['#f59e0b', '#fbbf24', '#fffbeb'],
    previewColor: '#fffbeb',
    accent: '#d97706',
    isDark: false,
    category: 'industry',
    emoji: '🍽️',
    cssVars: {
      '--app-bg': '#fffbeb',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#fef3c7',
      '--app-border': '#fde68a',
      '--app-text': '#78350f',
      '--app-text-secondary': '#b45309',
      '--accent': '#d97706',
    }
  },
  {
    id: 'education-school',
    name: 'تعليم ومدرسة',
    description: 'أزرق تعليمي هادئ للمدارس.',
    colors: ['#3b82f6', '#60a5fa', '#eff6ff'],
    previewColor: '#eff6ff',
    accent: '#2563eb',
    isDark: false,
    category: 'industry',
    emoji: '📚',
    cssVars: {
      '--app-bg': '#eff6ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#dbeafe',
      '--app-border': '#bfdbfe',
      '--app-text': '#1e3a8a',
      '--app-text-secondary': '#1d4ed8',
      '--accent': '#2563eb',
    }
  },
  {
    id: 'automotive-car',
    name: 'سيارات و قطع غيار',
    description: 'أزرق داكن احترافي لصناعة السيارات.',
    colors: ['#1d4ed8', '#3b82f6', '#dbeafe'],
    previewColor: '#dbeafe',
    accent: '#1e40af',
    isDark: false,
    category: 'industry',
    emoji: '🚗',
    cssVars: {
      '--app-bg': '#dbeafe',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#bfdbfe',
      '--app-border': '#93c5fd',
      '--app-text': '#1e3a8a',
      '--app-text-secondary': '#1d4ed8',
      '--accent': '#1e40af',
    }
  }
];
